### ISSUE TITLE
Homebridge crashes if Nuki Smart Lock is not present

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nuki#12]
Hi Lukas,

I had to disassemble my Nuki Smart Lock yesterday because of an issue with my door. So it is now offline with its batteries removed.
I think the plugin doesn't like it when it cannot reach a configured lock. Is it possible ignore the lock temporarily when it cannot be reached?
Homebridge running into a crash loop is not optimal in this case, because I have to be able to change the batteries etc.

Thank you very much!

`[2019-10-4 07:09:41] [NukiPlatform] Device with Nuki ID XXXXXXXXX and name Wohnungstür is a SmartLock.
[2019-10-4 07:09:41] TypeError: Cannot read property 'state' of undefined
    at NukiSmartLockDevice.update (/usr/local/lib/node_modules/homebridge-nuki/index.js:769:13)
    at new NukiSmartLockDevice (/usr/local/lib/node_modules/homebridge-nuki/index.js:757:10)
    at Object.callback (/usr/local/lib/node_modules/homebridge-nuki/index.js:147:31)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nuki/index.js:1026:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nuki/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nuki/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
[2019-10-4 07:09:41] Got SIGTERM, shutting down Homebridge...
`

**Comment by lukasroegner** [comment]
@felixmueller can you try the `development` branch? Should prevent the error now.

**Comment by lukasroegner** [comment]
Merged into master in #14.

**Comment by felixmueller** [comment]
Thank you very much for the fix! Sorry to not try it out in the first place, I didn’t want to recalibrate my lock again 😊
