### ISSUE TITLE
Problems with Docker?

### ISSUE THREAD

**Issue by henkhb** [lukasroegner/homebridge-nuki#51]
Hey, iam using Homebridge in a Docker on a Synology NAS.
After adding the ID of my opener, the plugin prevents the server to start:

AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:235:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at new NukiOpenerDevice (/usr/local/lib/node_modules/homebridge-nuki/src/nuki-opener-device.js:28:25)
    at Object.callback (/usr/local/lib/node_modules/homebridge-nuki/src/nuki-platform.js:137:39)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nuki/src/nuki-bridge-client.js:106:18)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nuki/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nuki/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nuki/node_modules/request/request.js:1076:12)

Any idea?

Thanks!

**Comment by lukasroegner** [comment]
The error means that the plugin does not get a proper name for the opener back from the API, do you have a name set in the Nuki app? Another thing I can think of: have you added the correct port forwarding to the Nuki bridge?

**Comment by henkhb** [comment]
Hey Lukas, thanks for your quick reply and your great work. There was no name for the opener set in the app. Corrected that. Also did a port forwarding and now its working as it should. Please close! Thanks!
